### ISSUE TITLE
storage.json

### ISSUE THREAD

**Issue by stealwin** [zume2020/Telegram-bot-Google-Drive#13]
For what need this file?I cant find it in project? i need to create this by myself?

**Comment by zume2020** [comment]
no, you don't have to create that file. I think that is automatically created when you authenticate the application.
BTW, are you getting any errors?

**Comment by stealwin** [comment]
> no, you don't have to create that file. I think that is automatically created when you authenticate the application.
> BTW, are you getting any errors?

i'm trying integrate your part code of posting image in google drive from bot with telebot

**Comment by zume2020** [comment]
You can just ignore storage.json

**Comment by stealwin** [comment]
why you didn't use pyTelegramBotAPI in your example?

**Comment by zume2020** [comment]
I felt the currently used library pretty good when I started the project, they have good docs and a pretty good developer community in telegram. that's why I chose it.

**Comment by stealwin** [comment]
i want my bot which using pyTelegramBotAPI i need to integrate part for posting document in google drive of your code
