### ISSUE TITLE
I get the following error once the bot starts uploading the file.

### ISSUE THREAD

**Issue by dhekabai** [zume2020/Telegram-bot-Google-Drive#4]
2020-05-30 14:17:15,370 - telegram.ext.dispatcher - ERROR - No error handlers ar
e registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\####\AppData\Roaming\Python\Python37\site-packages\telegram\e
xt\dispatcher.py", line 343, in process_update
    handler.handle_update(update, self, check, context)
  File "C:\Users\####\AppData\Roaming\Python\Python37\site-packages\telegram\e
xt\handler.py", line 119, in handle_update
    return self.callback(update, context)
  File "bot.py", line 42, in file_handler
    request = DRIVE.files().create(body=metadata,
AttributeError: 'Resource' object has no attribute 'create'

**Comment by zume2020** [comment]
Sorry for late reply, have you installed all the dependencies.

**Comment by dhekabai** [comment]
Yes, doesn't python install them automatically when I install the bot?

**Comment by dhekabai** [comment]
> Sorry for late reply, have you installed all the dependencies.

Yes, doesn't python install them automatically when I install the bot?

**Comment by zume2020** [comment]
have you fix it?

**Comment by dhekabai** [comment]
Nope, still having the same problem :/

**Comment by dhekabai** [comment]
> have you fix it?

Nope, still the same error :/

**Comment by zume2020** [comment]
bro, i have updated the code
pls have a look on it, hope the issue fixed.

**Comment by Akhilesh-Bayadi** [comment]
hello there!! i am getting some  errors while running "pip install -r requirements.txt" cmd:(

**Comment by zume2020** [comment]
> hello there!! i am getting some errors while running "pip install -r requirements.txt" cmd:(... can you help me out;)

Yess, whats the error?
